### ISSUE TITLE
[Error] telomerecat stopped unexpectedly, sorry!

### ISSUE THREAD

**Issue by julietluft** [jhrf/telomerecat#12]
Hi, I'm attempting to run telomerecat bam2length for the first time and am running into errors.
My command is:

`telomerecat bam2length -v2 /hps/nobackup2/flicek/user/mst/lce-si/data/bams/92058_N1.wgs.bam`

And my output:
```
telomerecat bam2length has started. Start Time: 2021-10-13 16:56:58
-------------------------------------------------------------------

DEBUG: Starting telbam generation for 1 inputs
DEBUG: Inline execution of telbam generation, 2 threads per process

[Error] telomerecat stopped unexpectedly, sorry!
Traceback (most recent call last):
  File "parabam/core.pyx", line 61, in parabam.core.CmdLineInterface.handle
  File "/hps/nobackup2/flicek/user/juliet/src/miniconda3/lib/python3.9/site-packages/telomerecat/bam2length.py", line 42, in run_cmd
    self.run(
  File "/hps/nobackup2/flicek/user/juliet/src/miniconda3/lib/python3.9/site-packages/telomerecat/bam2length.py", line 78, in run
    out_files = telbam_interface.run(input_paths=input_paths, outbam_dir=outbam_dir)
  File "/hps/nobackup2/flicek/user/juliet/src/miniconda3/lib/python3.9/site-packages/telomerecat/bam2telbam.py", line 101, in run
    telbam_paths = telbam.process_alignments(outbam_dir, self.total_procs, self.temp_dir, input_paths, reference=reference, verbose=self.verbose)
  File "/hps/nobackup2/flicek/user/juliet/src/miniconda3/lib/python3.9/site-packages/telomerecat/telbam.py", line 125, in process_alignments
    telbam_path = to_telbam(xam_file, outbam_dir=outbam_dir, tmpdir=tmpdir, hts_processes=hts_processes, reference=reference)
  File "/hps/nobackup2/flicek/user/juliet/src/miniconda3/lib/python3.9/site-packages/telomerecat/telbam.py", line 92, in to_telbam
    pairs_to_telbam(af_pairs, af_telbam)
  File "/hps/nobackup2/flicek/user/juliet/src/miniconda3/lib/python3.9/site-packages/telomerecat/telbam.py", line 68, in pairs_to_telbam
    af_telbam.write(read_b)
  File "pysam/libcalignmentfile.pyx", line 1709, in pysam.libcalignmentfile.AlignmentFile.write
  File "pysam/libcalignmentfile.pyx", line 1741, in pysam.libcalignmentfile.AlignmentFile.write
OSError: sam_write1 failed with error code -1
OSError: [Errno 0] Success
Exception ignored in: 'pysam.libcalignmentfile.AlignmentFile.__dealloc__'
Traceback (most recent call last):
  File "/hps/nobackup2/flicek/user/juliet/src/miniconda3/bin/telomerecat", line 31, in handle_input
    cmd_interface.handle(command_map, help_text)
OSError: [Errno 0] Success
(base) [juliet@hh-yoda-04-03 juliet]$ Traceback (most recent call last):
  File "/hps/nobackup2/flicek/user/juliet/src/miniconda3/bin/pysam_collate", line 8, in <module>
    sys.exit(thin_wrap())
  File "/hps/nobackup2/flicek/user/juliet/src/miniconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/hps/nobackup2/flicek/user/juliet/src/miniconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/hps/nobackup2/flicek/user/juliet/src/miniconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/hps/nobackup2/flicek/user/juliet/src/miniconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/hps/nobackup2/flicek/user/juliet/src/miniconda3/lib/python3.9/site-packages/telomerecat/pysam_collate.py", line 27, in thin_wrap
    pysam.collate(*collate_opts)
  File "/hps/nobackup2/flicek/user/juliet/src/miniconda3/lib/python3.9/site-packages/pysam/utils.py", line 69, in __call__
    raise SamtoolsError(
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=[collate] ERROR: could not write r1 alignment.\n'

```

I have tried with multiple different BAM files, and get the same output. So, I assume there is some kind of incompatibility between telomerecat and my set up.
Any idea what might be causing the issue and how I can fix it?

**Comment by jhrf** [comment]
Hi Juliet Luft,

Telomerecat is now maintained over at this repo: [https://github.com/cancerit/telomerecat](https://github.com/cancerit/telomerecat) . If problems persist I would recommend raising an issue over there.

After a quick glance at the error message it looks like you are failing to write an output. Does telomerecat or your user account have write permission to the directory that you are operating in? 

All the best!
