### ISSUE TITLE
Telomerecat crashes due to numpy issue

### ISSUE THREAD

**Issue by edawson** [jhrf/telomerecat#4]
I tried to run telomerecat on both a Dockerized Ubuntu system and locally on my Mac, but received the following error during the telbam2length step:

```
Traceback (most recent call last):
  File "parabam/core.pyx", line 49, in parabam.core.CmdLineInterface.handle (parabam/core.c:3184)
  File "/Users/dawsonet/anaconda3/envs/py27/lib/python2.7/site-packages/telomerecat/telbam2length.py", line 901, in run_cmd
    inserts_path=self.cmd_args.insert)
  File "/Users/dawsonet/anaconda3/envs/py27/lib/python2.7/site-packages/telomerecat/telbam2length.py", line 945, in run
    vital_stats = vital_stats_finder.get_vital_stats(sample_path)
  File "/Users/dawsonet/anaconda3/envs/py27/lib/python2.7/site-packages/telomerecat/telbam2length.py", line 467, in get_vital_stats
    vital_stats = self.__csv_to_dict__(vital_stats_csv)
  File "/Users/dawsonet/anaconda3/envs/py27/lib/python2.7/site-packages/telomerecat/telbam2length.py", line 441, in __csv_to_dict__
    self.__get_mean_and_sd__(ins_sum, ins_power_2, ins_N)
  File "/Users/dawsonet/anaconda3/envs/py27/lib/python2.7/site-packages/telomerecat/telbam2length.py", line 460, in __get_mean_and_sd__
    x_sd = npy.sqrt((x_N * x_power_2) - x_sum**2) / x_N
AttributeError: 'long' object has no attribute 'sqrt'

```

This seems to be a common issue with numpy, and the solution suggested on Stackoverflow was to cast doubles to floats. I hope the precision change doesn't affect the results, but I don't have a way to check.

I've made a pull request with the single line change that got things working on my system (PR #3 ).

**Comment by jhrf** [comment]
Hey thanks so much for taking the time to fix this issue. I've checked your fix on my machine and it looks good. Merging to master.
